version: "3.8"

services:
  app:
    build:
      context: .
      target: ${TARGET:-development}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    env_file:
      - .env.local
    command: ${COMMAND:-npm run dev}
